### ISSUE TITLE
Write output functions

### ISSUE THREAD

**Issue by aremazeilles** [eurobench/pi_octave_csic#2]
Look at https://github.com/eurobench/pi_octave_csic/blob/master/src/computePI.m#L76
We are likely to suggest such type of operation to several projects.

Would be good thus to write this as a functions, so that people can more easily copy the function in their code. 

ping @alfonsotecnalia 
If you agree, I can work on that.

**Comment by alfonsotecnalia** [comment]
I agree on this. It would be very helpful for people. Go ahead!
