### ISSUE TITLE
CI github

### ISSUE THREAD

**Issue by aremazeilles** [eurobench/pi_octave_csic#4]
Two solutions ca be considered here:

* use travis, as I do in the [ROS package generator](https://github.com/tecnalia-advancedmanufacturing-robotics/ros_pkg_gen)
* go for the [github actions](https://help.github.com/en/actions)

In both cases, I think the CI process would be done through docker (while in Gitlab we are still using a "real" machine).

That makes the process is bit different, because in gitlab, I guess the docker generation was done using layers already present in the local docker image (and thus speeding the process).

A first trial could be to let the generation as is, but it means that everytime it is launched, it would start from the basic docker image, and thus takes more time.

Also we have 3 jobs right now: `build` -> `test` -> `deploy`.
With the githlab "real machine", the image generated at the `build` stage is used by the `test` stage, and then deployed in the last stage. 
This is unclear to me whether jobs under travis / github can have a similar behaviour. 

We may need a different strategy here:

* at build stage, build and push it on a docker server, with an unstable tag
* in the test stage, get the unstable docker from the server, and test it it
* in the deploy stage, basically get out the unstable tag

ping @alfonsotecnalia to share these thoughts.

In any case, going right now to create an eurobench-test place on docker for making trials

**Comment by alfonsotecnalia** [comment]
I don't know either of the options so I don't have a strong opinion on them. If I were you, I suppose I would go ahead with the known option (travis).

**Comment by aremazeilles** [comment]
well... I have been looking at the github actions, as you can see here: https://github.com/eurobench/pi_octave_csic/pull/5

**Comment by aremazeilles** [comment]
#7 provides a first answer. There is a unique job, and that could be better organised, but.. this is a good start!

**Comment by aremazeilles** [comment]
I assume this is is now solved.
